Add LCP support
NYPL-Simplified/opds-web-client pull request #279
Opened 2020-08-25 10:26 UTC by vbessonov

## Description

This PR adds support for LCP license files (`application/vnd.readium.lcp.license.v1.0+json`) returned by Circulation Manager during fulfilment of LCP protected books.

2020-09-21 14:43 UTC, vbessonov commented
@hokei, could you review this PR?

2020-09-22 09:42 UTC, kristojorg commented
@vbessonov While this will allow a button labeled "LCP License" to show in the UI, I don't think this is the right approach for LCP content, as it doesn't mean anything to the user. How does LCP content work? Does the user download a license file? What do they do with it from there?

2020-09-22 09:42 UTC, kristojorg requested changes
I think we need a better understanding of how this should work from a user perspective before we support LCP files in the web client

2020-09-22 10:10 UTC, vbessonov commented
@kristojorg, you can find a detailed description [here](https://github.com/vbessonov/circulation-lcp-test#test).

Also, you can download an LCP book from the [LCP testbed](http://cm.se-community-lcp-test.lyrtech.org/admin/web/collection/LCP) (you can find its description and credentials in the [Lyrasis wiki](https://wiki.lyrasis.org/display/SIM/How+LCP+works+in+SimplyE)). Once you download a book, you can notice that it doesn't have an extension and because of that it cannot be opened in Thorium or other LCP-compatible client applications without manually adding an extension. This PR force opds-web-client to add `.lcpl` extension to the LCP books

2020-09-22 11:40 UTC, kristojorg approved these changes
Approving this because it matches our level of support for ACSM. In the future we should show users how to deal with these files, though

2020-09-23 18:42 UTC, EdwinGuzman commented
@vbessonov I can merge this in but can you update the version in `packages/opds-web-client/package.json` and also update  `packages/opds-web-client/changelog`?

2020-09-23 19:49 UTC, vbessonov commented
@EdwinGuzman, sure, should I increase the minor version or the patch one?

2020-09-24 02:48 UTC, EdwinGuzman commented
I think a patch one is fine for this.

2020-09-24 06:32 UTC, vbessonov commented
@EdwinGuzman, sure, will do. Could you tell me how I should update version in `package-lock.json`?
I tried to use `npm update` and `npm install --package-lock-only` but none of them worked. Can I update `package-lock.json` manually?

2020-09-24 13:04 UTC, EdwinGuzman commented
You can update it manually if you update the version in `package.json`, then delete `package-lock.json`, and then run `npm install` again.

2020-09-24 13:36 UTC, vbessonov commented
@EdwinGuzman, I tried to delete `package-lock.json` and then run `npm install` but it didn't work, new `package-lock.json` for some reason wasn't created. So I ended up with manually updating the version in `package-lock.json`, I hope it won't break anything

2020-09-24 13:46 UTC, EdwinGuzman approved these changes
Great, thanks.

2020-09-24 13:46 UTC, merged

2020-09-24 14:03 UTC, EdwinGuzman commented
Just published `0.5.7` to npm.